#!/usr/bin/env bash

here=$(cd $(dirname "$0"); /bin/pwd)

# usage: run_cmake-osx [-g]

tmp=tmp
buildtype=Release

if [[ $1 = -g ]]; then
    tmp=tmp_debug
    buildtype=Debug
    shift
fi

os=$(IFS=. read -r a b _ < <(sysctl -n kern.osproductversion); printf "%03d" "$a" "$b")
sonoma=014000
cmake_extra_args=()
if [[ $os > $sonoma || $os == $sonoma ]]; then
    cmake_extra_args+=(-DCMAKE_OSX_DEPLOYMENT_TARGET=14.0)
fi

# Build for the host architecture by default (matches a stock Homebrew install).
# For a distributable universal binary, override e.g. APPLE_ARCH="arm64;x86_64"
# -- that requires universal builds of wxWidgets/cfitsio/libusb/libnova too.
APPLE_ARCH=${APPLE_ARCH:-$(uname -m)}

WXWIN=$(wx-config --prefix)
[[ -d $WXWIN ]] || {
    echo "could not find wxWidgets installation" >&2
    exit 1
}

set -e

cd "$here"
mkdir -p "$tmp"
cd "$tmp"

cmake -G "Unix Makefiles" \
    -DCMAKE_OSX_ARCHITECTURES="$APPLE_ARCH" \
    -DCMAKE_BUILD_TYPE="$buildtype" \
    "${cmake_extra_args[@]}" \
    "$@" \
    ..
